### ISSUE TITLE
留言内容可以内嵌html代码

### ISSUE THREAD

**Issue by CatchBear** [xiyouant/Checkout#8]
#### 留言内容可以潜入html代码，并且这些代码浏览器会解析执行

> ```
> 如<p style="font-size:100px";> 特殊字体</p> 
> ```
> 
> 对html进行内嵌css修饰，留言内容会编成如css设置的样式，并不是规定的默认样式
#### 留言内容同样可以添加图片源

> 添加的图片可能会浮动在其他人的留言上面，并不是只在自己的留言区间，当时是这样，其他人的界面貌似没有刷出来我的那张图片，但是有图片加载失败的默认样式，说明是能加载图片的。

**Comment by magichan** [comment]
更新版本后解决
